export const CODE_STATUS_LOCAL_PAYMENT = {
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
  LINK_NOT_FOUND: "LINK_NOT_FOUND",
  LINK_EXPIRED: "LINK_EXPIRED",
  PAYMENT_ERROR: "PAYMENT_ERROR",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
};
